# Generated by Django 3.0.7 on 2020-07-04 03:43

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_insumo_insumomedico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('correo', models.CharField(max_length=30)),
                ('especialidad', models.CharField(max_length=20)),
                ('fecha_atencion', models.DateField()),
                ('hora_atencion', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='insumo',
            name='cantidad',
            field=models.IntegerField(),
        ),
    ]
