# Generated by Django 3.0.7 on 2020-07-05 17:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_reserva1'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='odontologo',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
